<a href="https://colab.research.google.com/github/HARRY-hussein/ai_foundation/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np

# 1D massiv yaratish
arr = np.array([1, 3, 5, 7])
print('numpy_array:', arr)
# Natija: numpy_array: [1 3 5 7]

# Massiv o'lchami (1 ta o'lcham, 4 ta element)
arr.shape
# Natija: (4,)

In [ ]:
# 2D massiv yaratish
arr2 = np.array([[1, 3, 5, 7], [4, 6, 8, 9]])
print('numpy_array2:', arr2)
# Natija: 2 qator va 4 ustundan iborat matritsa

# O'lchamni ko'rish (2 ta qator, 4 ta ustun)
arr2.shape
# Natija: (2, 4)

In [ ]:
# Ma'lumotlar turini tekshirish
a = np.array([1, 2, 3])
print(a.dtype)
# Natija: int64 (64-bitli butun son)

In [ ]:
# Massiv shaklini o'zgartirish
a = np.array([1, 2, 3, 4, 5, 6])
# 6 ta elementni 2 qator va 3 ustunga o'tkazish
b = a.reshape(2, 3)
print("shaped_array:", b)
# Natija:
# [[1 2 3]
#  [4 5 6]]

In [ ]:
a = np.array([1, 2, 3])
# Elementlarni float (o'nli son) turiga o'tkazish
b = a.astype(float)
print("float:", b)
# Natija: float: [1. 2. 3.]

In [ ]:
# 2 qator va 3 ustundan iborat nol va birlardan iborat massivlar
z = np.zeros((2, 3))
o = np.ones((2, 3))

print("zeros:", z)
print("ones:", o)

In [ ]:
a = np.array([[1, 2], [3, 4]])
print("ndim:", a.ndim)
# Natija: 2

In [ ]:
# 1 dan 7 gacha (7 kirmaydi) bo'lgan sonlar
a = np.arange(1, 7)
print("arange:", a)
# Natija: [1 2 3 4 5 6]

In [ ]:
a = np.array([1, 2, 3, 4])

print("sum:", a.sum())   # Yig'indisi: 10
print("mean:", a.mean()) # O'rtachasi: 2.5
print("max:", a.max())   # Eng kattasi: 4
print("min:", a.min())   # Eng kichigi: 1

In [ ]:
a = np.array([[1, 2], [3, 4]])
# 2D massivni 1D massivga tekislash
print('flatten:', a.flatten())
# Natija: [1 2 3 4]

In [ ]:
a = np.array([[1, 2], [3, 4]])
# Qator va ustunlarni almashtirish
print("transpose:", a.T)
# Natija:
# [[1 3]
#  [2 4]]

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 0], [1, 2]])

# Matritsalarni ko'paytirish: (a * b)
print("dot/multiplication:", a.dot(b))
# Natija:
# [[4 4]
#  [10 8]]

In [ ]:
# 2 qator va 3 ustundan iborat tasodifiy sonlar massivi
a = np.random.rand(2, 3)
print("random rand:", a)